<?php
/**
 * Buyitdirect Group
 *
 * @category    BuyIt
 * @package     HyvaCandidateTest
 * @copyright   Copyright (c) 2025-current Buyitdirect Group (https://www.buyitdirectgroup.co.uk/)
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use BuyIt\HyvaCandidateTest\ViewModel\CarouselProducts;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var CarouselProducts $carouselProducts */
$carouselProducts = $viewModels->require(CarouselProducts::class);

$sliderName = preg_replace('/[.\/\\\\]/', '_', $block->getNameInLayout());
$columnCount = $block->getData('column_count') ?: 8;
$sliderClasses = array_filter([
	'relative shrink-0 flex flex-col px-2 w-full',
	$columnCount >= 2 ? 'md:w-1/2' : '',
	$columnCount >= 3 ? 'lg:w-1/4' : ''
]);
$title = 'You may be interested in these';
$type = 'generic';

$items = $carouselProducts->getTestProducts();
?>

<?php if ($items): ?>
    <section
            id="<?= /* @noEscape */ $sliderName ?>"
            class="product-slider buy-it-product-slider relative my-8"
            aria-label="<?= $escaper->escapeHtmlAttr($title); ?>"
            data-slider-type="<?= $escaper->escapeHtmlAttr($type) ?>"
            x-data
            x-snap-slider.group-pager
            x-defer="intersect"
    >
        <a
                href="#<?= $escaper->escapeHtmlAttr($sliderName) ?>-slider-end"
                class="sr-only focus:not-sr-only  focus:z-10 focus:absolute focus:inset-x-0
            focus:w-fit focus:mx-auto focus:py-2 focus:px-4 focus:bg-white"
        ><?= $escaper->escapeHtml(__('Press to skip carousel')) ?></a>
        <div class="flex gap-2 justify-between items-center mb-2 pb-4 border-b-2 border-gray-300">
            <h3 class="text-2xl font-medium text-gray-900 title-font">
			    <?= $escaper->escapeHtml($title); ?>
            </h3>
        <div class="flex gap-2">
            <button
                    class="btn btn-secondary p-2 invisible"
                    aria-label="Previous Slide"
                    data-prev
                    disabled
            ><?= $heroicons->chevronLeftHtml('rtl:-rotate-180', 18, 18, ['aria-hidden' => 'true']); ?></button>
            <button
                    class="btn btn-secondary p-2 invisible"
                    aria-label="Next Slide"
                    data-next
                    disabled
            ><?= $heroicons->chevronRightHtml('rtl:-rotate-180', 18, 18, ['aria-hidden' => 'true']); ?></button>
        </div>
        </div>
        <div data-track class="group js_slides flex snap overflow-x-auto py-4 -mx-1">
			<?php foreach ($items as $product): ?>
                <div
                        id="<?= $sliderName . '-' . $product['id'] ?>"
                        class="<?= $escaper->escapeHtmlAttr(implode(' ', $sliderClasses)) ?>"
                >
                    <!-- Card -->
                    <div class="relative h-full p-4 flex flex-col"
                         x-data="{ added: false, modalIsOpen: false }">
                        <!-- Save Badge -->
                        <div class="absolute -top-2 left-3">
                            <div class="relative z-10 bg-yellow-500 px-2 py-1 w-16 font-bold leading-5 text-center">
								<?= $product['product_label'] ?>
                            </div>
                            <span class="-mt-6 bg-yellow-500 block h-12 mx-auto rotate-45 w-12"></span>
                        </div>

                        <!-- Image -->
                        <div class="mt-4 mb-3">
                            <a href="#" title="<?= $escaper->escapeHtmlAttr($product['name']); ?>"
                               onclick="event.preventDefault();"
                               x-on:click="modalIsOpen = true">
                                <img src="<?= $escaper->escapeHtmlAttr($product['img_url']) ?>"
                                     alt="<?= $escaper->escapeHtmlAttr($product['name']); ?>"
                                     class="w-full h-44 object-cover rounded-md"/>
                            </a>
                        </div>

                        <!-- Product Title -->
                        <a href="#" onclick="event.preventDefault();"
                           x-on:click="modalIsOpen = true" title="<?= $escaper->escapeHtmlAttr($product['name']); ?>"
                           class="font-medium leading-snug mb-2" >
                            <span class="text-primary hover:text-red-600"><?= $escaper->escapeHtml($product['name']); ?></span>
                        </a>

                        <!-- Prices -->
                        <div class="mb-2">
                            Regular price £<?= $escaper->escapeHtml($product['price']) ?>
                        </div>
                        <?php if (isset($product['special_price'])): ?>
                            <div class="">
                                <span class="text-slate-800">Sale price</span><br>
                                <span class="font-bold text-red text-2xl ml-1">£<?= $escaper->escapeHtml($product['special_price']); ?></span>
                                <span class="text-slate-500 ml-1">Ex vat</span>
                            </div>
                        <?php endif; ?>

                        <!-- Add Button -->
                        <div class="mt-auto">
                            <button type="button" class="mt-2 bg-black inline-flex items-center justify-center gap-2 rounded-full
                            px-8 py-2 font-bold text-white hover:bg-primary/10 transition
                            focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-900"
                                    @click="added = !added"
                            >
                                <template x-if="added">
									<?= $heroicons->checkHtml('', 18, 18, ['aria-hidden' => 'true']); ?>
                                </template>
                                <template x-if="added == false">
									<?= $heroicons->plusHtml('', 18, 18, ['aria-hidden' => 'true']); ?>
                                </template>
                                <span x-text="added ? 'Product Added' : 'Add'"></span>
                            </button>
                        </div>

                        <div x-show="modalIsOpen" x-transition.opacity.duration.200ms=""
                             x-on:keydown.esc.window="modalIsOpen = false"
                             x-on:click.self="modalIsOpen = false"
                             class="popup-wrapper fixed inset-0 z-30 flex items-center justify-center bg-black/50 p-8 backdrop"
                             role="dialog" aria-modal="true">
                            <div x-show="modalIsOpen"
                                 x-transition:enter="transition ease-out duration-200 delay-100 motion-reduce:transition-opacity"
                                 x-transition:enter-start="opacity-0 scale-50"
                                 x-transition:enter-end="opacity-100 scale-100"
                                 class="relative flex justify-center max-h-full max-w-full md:max-w-lg lg:max-w-2xl flex-col gap-1 px-6 py-8 overflow-auto bg-white shadow" >
                                <button x-on:click="modalIsOpen = false" class="absolute mt-2 top-0 right-2 hover:text-red-600" aria-label="close modal">
									<?= $heroicons->xHtml('', 18, 18, ['aria-hidden' => 'true']); ?>
                                </button>

                               <img src="<?= $escaper->escapeHtmlAttr($product['img_url']) ?>"
                                    alt="<?= $escaper->escapeHtmlAttr($product['name']); ?>"
                                    class="w-auto h-auto object-cover rounded-md"/>
                               <div>
                                   <span class="font-bold"><?= $escaper->escapeHtml(__('Name'))?></span>: <span class="text-primary"><?= $escaper->escapeHtml($product['name']); ?></span>
                               </div>
                               <div>
                                   <span class="font-bold"><?= $escaper->escapeHtml(__('Description'))?></span>: <span class="text-primary"><?= $escaper->escapeHtml($product['short_description']); ?></span>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
			<?php endforeach; ?>
        </div>
        <div data-pager class="hidden md:flex flex-wrap justify-center gap-2 py-2 min-h-11">
			<?php
			$pagerIndex = 0;
			foreach ($items as $product):
				?>
                <button
                        class="shrink-0 w-3 h-3 m-2 rounded-full bg-slate-400 cursor-point transition-[background-color,width,outline-offset]
                    focus:outline-offset-4 focus:outline-slate-700
                    aria-[current=true]:bg-slate-700 aria-[current=true]:w-6"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('View more about %1', $product['name'])) ?>"
                        data-target-id="<?= $sliderName . '-' . $product['id'] ?>"
                        x-cloak
					<?php if ($pagerIndex === 0): ?>
                        aria-current="true"
					<?php endif; ?>
                ></button>
				<?php
				$pagerIndex++;
			endforeach;
			?>
        </div>
        <span id="<?= $escaper->escapeHtmlAttr($sliderName) ?>-slider-end" tabindex="-1"></span>
    </section>
<?php endif; ?>